<?php

declare(strict_types=1);

namespace Tapbuy\DataScrubber\Tests;

use Faker\Factory as FakerFactory;
use Faker\Generator;
use PHPUnit\Framework\TestCase;
use Tapbuy\DataScrubber\Anonymizer;
use Tapbuy\DataScrubber\Keys;

/**
 * Tests Anonymizer against a realistic log structure generated by FakerPHP.
 *
 * Log entries mirror the shape observed in var/logs.json:
 * [ { timestamp, type, operation, request_path, variables, result, execution_time_ms } ]
 *
 * Sensitive keys configured: email, password, firstname, lastname, telephone
 */
class LogAnonymizerTest extends TestCase
{
    private Anonymizer $anonymizer;
    private Generator $faker;

    /** Keys that match real field names in the GraphQL log payloads */
    private const SENSITIVE_KEYS = ['email', 'password', 'firstname', 'lastname', 'telephone'];

    protected function setUp(): void
    {
        $this->faker = FakerFactory::create();

        $keysMock = $this->createMock(Keys::class);
        $keysMock->method('getKeys')->willReturn(self::SENSITIVE_KEYS);

        $this->anonymizer = new Anonymizer($keysMock);
    }

    // ── Helpers ──────────────────────────────────────────────────────────

    private function masked(string $value): string
    {
        return str_repeat('*', mb_strlen($value));
    }

    private function makeAddress(): array
    {
        return [
            'id'               => $this->faker->numberBetween(1000000, 9999999),
            'prefix'           => null,
            'firstname'        => $this->faker->firstName(),
            'lastname'         => $this->faker->lastName(),
            'street'           => [$this->faker->streetName(), (string) $this->faker->buildingNumber()],
            'city'             => $this->faker->city(),
            'postcode'         => $this->faker->postcode(),
            'country_id'       => $this->faker->countryCode(),
            'telephone'        => $this->faker->phoneNumber(),
            'default_billing'  => false,
            'default_shipping' => false,
            'region'           => ['region' => null, 'region_code' => null, 'region_id' => 0],
        ];
    }

    private function makeCustomer(bool $withAddresses = true): array
    {
        $firstName = $this->faker->firstName();
        $lastName  = $this->faker->lastName();
        $email     = $this->faker->email();

        $customer = [
            'firstname'       => $firstName,
            'lastname'        => $lastName,
            'email'           => $email,
            'date_of_birth'   => null,
            'is_subscribed'   => false,
            'gender'          => null,
            'created_at'      => $this->faker->dateTime()->format('Y-m-d H:i:s'),
            'is_new_customer' => false,
            'last_order_date' => $this->faker->dateTime()->format('Y-m-d H:i:s'),
            'last_visit_date' => null,
        ];

        if ($withAddresses) {
            $customer['addresses'] = array_map(
                fn() => $this->makeAddress(),
                range(1, $this->faker->numberBetween(1, 3))
            );
        }

        return $customer;
    }

    private function makeLogEntry(string $operation, string $type, array $variables, array $result): array
    {
        return [
            'timestamp'        => $this->faker->dateTime()->format('Y-m-d H:i:s.u'),
            'type'             => $type,
            'operation'        => $operation,
            'request_path'     => '/r/retailer-dev/cart/' . $this->faker->uuid(),
            'variables'        => $variables,
            'result'           => $result,
            'execution_time_ms' => round($this->faker->randomFloat(2, 50, 2000), 2),
        ];
    }

    // ── tapbuyModulesVersions (no PII) ───────────────────────────────────

    public function testModulesVersionsEntryIsUntouched(): void
    {
        $entry = $this->makeLogEntry(
            operation: 'tapbuyModulesVersions',
            type: 'query',
            variables: [],
            result: [
                'data' => [
                    'tapbuyModulesVersions' => [
                        ['enabled' => true, 'name' => 'tapbuy/checkout-graphql', 'version' => '1.9.0'],
                        ['enabled' => true, 'name' => 'tapbuy/adyen',            'version' => '1.4.1'],
                    ],
                ],
            ]
        );

        $logs   = [$entry];
        $result = $this->anonymizer->anonymizeObject($logs);

        // Metadata fields untouched
        $this->assertSame($entry['timestamp'],         $result[0]['timestamp']);
        $this->assertSame($entry['type'],              $result[0]['type']);
        $this->assertSame($entry['operation'],         $result[0]['operation']);
        $this->assertSame($entry['request_path'],      $result[0]['request_path']);
        $this->assertSame($entry['execution_time_ms'], $result[0]['execution_time_ms']);

        // No-PII result data untouched
        $modules = $result[0]['result']['data']['tapbuyModulesVersions'];
        $this->assertSame('tapbuy/checkout-graphql', $modules[0]['name']);
        $this->assertSame('1.9.0',                   $modules[0]['version']);
        $this->assertTrue($modules[0]['enabled']);
    }

    // ── getCustomer ───────────────────────────────────────────────────────

    public function testGetCustomerMasksCustomerPiiFields(): void
    {
        $customer = $this->makeCustomer(withAddresses: false);

        $entry = $this->makeLogEntry(
            operation: 'getCustomer',
            type: 'query',
            variables: ['withAddresses' => false, 'customerToken' => true],
            result: ['data' => ['customer' => $customer]]
        );

        $result   = $this->anonymizer->anonymizeObject([$entry]);
        $anon     = $result[0]['result']['data']['customer'];

        $this->assertSame($this->masked($customer['firstname']), $anon['firstname']);
        $this->assertSame($this->masked($customer['lastname']),  $anon['lastname']);
        $this->assertSame($this->masked($customer['email']),     $anon['email']);

        // Non-PII fields in customer untouched
        $this->assertSame($customer['is_subscribed'],  $anon['is_subscribed']);
        $this->assertSame($customer['is_new_customer'], $anon['is_new_customer']);
        $this->assertNull($anon['date_of_birth']);
    }

    public function testGetCustomerMasksAddressesPiiFields(): void
    {
        $customer = $this->makeCustomer(withAddresses: true);

        $entry = $this->makeLogEntry(
            operation: 'getCustomer',
            type: 'query',
            variables: ['withAddresses' => true, 'customerToken' => true],
            result: ['data' => ['customer' => $customer]]
        );

        $result    = $this->anonymizer->anonymizeObject([$entry]);
        $addresses = $result[0]['result']['data']['customer']['addresses'];

        foreach ($customer['addresses'] as $i => $addr) {
            $this->assertSame($this->masked($addr['firstname']),  $addresses[$i]['firstname'],  "address[$i] firstname");
            $this->assertSame($this->masked($addr['lastname']),   $addresses[$i]['lastname'],   "address[$i] lastname");
            $this->assertSame($this->masked($addr['telephone']),  $addresses[$i]['telephone'],  "address[$i] telephone");

            // Non-PII address fields untouched
            $this->assertSame($addr['id'],         $addresses[$i]['id'],         "address[$i] id");
            $this->assertSame($addr['city'],        $addresses[$i]['city'],        "address[$i] city");
            $this->assertSame($addr['postcode'],    $addresses[$i]['postcode'],    "address[$i] postcode");
            $this->assertSame($addr['country_id'],  $addresses[$i]['country_id'],  "address[$i] country_id");
        }
    }

    public function testGetCustomerLeavesVariablesUntouched(): void
    {
        $customer = $this->makeCustomer(withAddresses: false);

        $entry = $this->makeLogEntry(
            operation: 'getCustomer',
            type: 'query',
            variables: ['withAddresses' => true, 'customerToken' => true],
            result: ['data' => ['customer' => $customer]]
        );

        $result = $this->anonymizer->anonymizeObject([$entry]);

        $this->assertTrue($result[0]['variables']['withAddresses']);
        $this->assertTrue($result[0]['variables']['customerToken']);
    }

    // ── tapbuyCustomerSearch ──────────────────────────────────────────────

    public function testCustomerSearchMasksPiiInVariablesAndResult(): void
    {
        $customer  = $this->makeCustomer(withAddresses: false);
        $searchEmail = $customer['email'];

        $entry = $this->makeLogEntry(
            operation: 'tapbuyCustomerSearch',
            type: 'query',
            variables: ['email' => $searchEmail, 'withAddresses' => false],
            result: [
                'data' => [
                    'tapbuyCustomerSearch' => array_merge(
                        ['customer_id' => $this->faker->numberBetween(1000000, 9999999)],
                        $customer
                    ),
                ],
            ]
        );

        $result = $this->anonymizer->anonymizeObject([$entry]);

        // variables.email masked
        $this->assertSame($this->masked($searchEmail), $result[0]['variables']['email']);
        // variables.withAddresses untouched
        $this->assertFalse($result[0]['variables']['withAddresses']);

        // result PII masked
        $anon = $result[0]['result']['data']['tapbuyCustomerSearch'];
        $this->assertSame($this->masked($customer['firstname']), $anon['firstname']);
        $this->assertSame($this->masked($customer['lastname']),  $anon['lastname']);
        $this->assertSame($this->masked($customer['email']),     $anon['email']);

        // Non-PII result untouched
        $this->assertIsInt($anon['customer_id']);
    }

    // ── generateCustomerToken ─────────────────────────────────────────────

    public function testGenerateCustomerTokenMasksEmailAndPassword(): void
    {
        $email    = $this->faker->email();
        $password = $this->faker->password(8, 20);

        $entry = $this->makeLogEntry(
            operation: 'generateCustomerToken',
            type: 'mutation',
            variables: ['email' => $email, 'password' => $password],
            result: ['data' => ['generateCustomerToken' => ['token' => $this->faker->sha256()]]]
        );

        $result = $this->anonymizer->anonymizeObject([$entry]);

        $this->assertSame($this->masked($email),    $result[0]['variables']['email']);
        $this->assertSame($this->masked($password), $result[0]['variables']['password']);

        // Token is not a known key — untouched
        $this->assertSame(
            $entry['result']['data']['generateCustomerToken']['token'],
            $result[0]['result']['data']['generateCustomerToken']['token']
        );
    }

    // ── checkUserEmailExist ───────────────────────────────────────────────

    public function testCheckEmailMasksEmailVariable(): void
    {
        $email = $this->faker->email();

        $entry = $this->makeLogEntry(
            operation: 'checkUserEmailExist',
            type: 'query',
            variables: ['email' => $email],
            result: ['data' => ['checkUserEmailExist' => ['exists' => true]]]
        );

        $result = $this->anonymizer->anonymizeObject([$entry]);

        $this->assertSame($this->masked($email), $result[0]['variables']['email']);
        // Non-PII result untouched
        $this->assertTrue($result[0]['result']['data']['checkUserEmailExist']['exists']);
    }

    // ── adyenRedeemedGiftcards (no PII) ──────────────────────────────────

    public function testAdyenGiftcardsHasNoPiiAndIsUntouched(): void
    {
        $cartId = $this->faker->bothify('????????????????????????????????');

        $entry = $this->makeLogEntry(
            operation: 'adyenRedeemedGiftcards',
            type: 'query',
            variables: ['cartId' => $cartId],
            result: [
                'data' => [
                    'adyenRedeemedGiftcards' => [
                        'redeemedGiftcards' => [],
                        'remainingAmount'   => '€ 719,84',
                        'totalDiscount'     => '€ 0,00',
                    ],
                ],
            ]
        );

        $result = $this->anonymizer->anonymizeObject([$entry]);

        // cartId is not a sensitive key — untouched
        $this->assertSame($cartId, $result[0]['variables']['cartId']);
        $this->assertSame('€ 719,84', $result[0]['result']['data']['adyenRedeemedGiftcards']['remainingAmount']);
    }

    // ── Multi-entry log (mixed PII and non-PII entries) ───────────────────

    public function testMixedLogBatchAnonymizesCorrectlyAcrossEntries(): void
    {
        $customer = $this->makeCustomer(withAddresses: true);
        $searchEmail = $customer['email'];
        $loginEmail  = $this->faker->email();
        $password    = $this->faker->password();
        $cartId      = $this->faker->bothify('????????????????????????????????');

        $logs = [
            // Entry 0: no PII
            $this->makeLogEntry('tapbuyModulesVersions', 'query', [], [
                'data' => ['tapbuyModulesVersions' => [['enabled' => true, 'name' => 'tapbuy/adyen', 'version' => '1.4.1']]],
            ]),
            // Entry 1: getCustomer with addresses
            $this->makeLogEntry('getCustomer', 'query', ['withAddresses' => true, 'customerToken' => true], [
                'data' => ['customer' => $customer],
            ]),
            // Entry 2: tapbuyCustomerSearch
            $this->makeLogEntry('tapbuyCustomerSearch', 'query', ['email' => $searchEmail, 'withAddresses' => false], [
                'data' => ['tapbuyCustomerSearch' => $customer],
            ]),
            // Entry 3: generateCustomerToken
            $this->makeLogEntry('generateCustomerToken', 'mutation', ['email' => $loginEmail, 'password' => $password], [
                'data' => ['generateCustomerToken' => ['token' => 'abc123']],
            ]),
            // Entry 4: adyenRedeemedGiftcards — no PII
            $this->makeLogEntry('adyenRedeemedGiftcards', 'query', ['cartId' => $cartId], [
                'data' => ['adyenRedeemedGiftcards' => ['redeemedGiftcards' => [], 'remainingAmount' => '€ 0,00', 'totalDiscount' => '€ 0,00']],
            ]),
        ];

        $result = $this->anonymizer->anonymizeObject($logs);

        // Entry 0: no PII — operation and module name untouched
        $this->assertSame('tapbuyModulesVersions', $result[0]['operation']);
        $this->assertSame('tapbuy/adyen', $result[0]['result']['data']['tapbuyModulesVersions'][0]['name']);

        // Entry 1: customer PII masked, metadata untouched
        $this->assertSame('getCustomer', $result[1]['operation']);
        $this->assertSame($this->masked($customer['firstname']), $result[1]['result']['data']['customer']['firstname']);
        $this->assertSame($this->masked($customer['email']),     $result[1]['result']['data']['customer']['email']);
        foreach ($customer['addresses'] as $i => $addr) {
            $this->assertSame(
                $this->masked($addr['telephone']),
                $result[1]['result']['data']['customer']['addresses'][$i]['telephone']
            );
        }

        // Entry 2: variables.email masked
        $this->assertSame($this->masked($searchEmail), $result[2]['variables']['email']);
        $this->assertFalse($result[2]['variables']['withAddresses']);

        // Entry 3: variables.email and variables.password masked
        $this->assertSame($this->masked($loginEmail), $result[3]['variables']['email']);
        $this->assertSame($this->masked($password),   $result[3]['variables']['password']);
        // token is not a known key
        $this->assertSame('abc123', $result[3]['result']['data']['generateCustomerToken']['token']);

        // Entry 4: cartId is not a known key — untouched
        $this->assertSame($cartId, $result[4]['variables']['cartId']);

        // All metadata fields untouched across all entries
        foreach ($logs as $i => $entry) {
            $this->assertSame($entry['timestamp'],         $result[$i]['timestamp'],         "entry[$i] timestamp");
            $this->assertSame($entry['type'],              $result[$i]['type'],              "entry[$i] type");
            $this->assertSame($entry['operation'],         $result[$i]['operation'],          "entry[$i] operation");
            $this->assertSame($entry['request_path'],      $result[$i]['request_path'],       "entry[$i] request_path");
            $this->assertSame($entry['execution_time_ms'], $result[$i]['execution_time_ms'],  "entry[$i] execution_time_ms");
        }
    }
}
